# home page url: https://jfokus-app-3.com
# callback url: https://redhat-developer-hub-user29.apps.cluster-szxjh.szxjh.sandbox1303.opentlc.com/api/auth/github/handler/frame


kind: Secret
apiVersion: v1
metadata:
  name: rhdh-secrets-github-credentials
  namespace: demo-project #project-namespace
stringData:
  RHDH_GITHUB_ORGANIZATION: "workshop-devhub"
  RHDH_GITHUB_APP_ID: "1131846"
  RHDH_GITHUB_APP_CLIENT_ID: "Iv23liQt7ze4NNFl2jVr"
  RHDH_GITHUB_APP_CLIENT_SECRET: "1458701af8bfc7f22facbbacde1ea71ca0977686"
  RHDH_GITHUB_APP_PRIVATE_KEY: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEAwYjRX0VExOJJpLK/7v9hpvDN8XSyyEGEGl9EeUj/D06TKIUj
    8RR5+w3+uqvZjQULFCMr9+geupRZXvDdUpx9Iq6GsLmalbBiqJOuDy0J8nmfE6/o
    V8qsZ6SVXB5PtaoeExK6xl8oFlAAE2cC4r5S1mxwXjy7UieYaFEMaqbQN/Pu0hsx
    9eShv7DCMKIr3ISBWsWxJej2kgEP+tKdj2VreZUL+hQbAob2ZQuZWKTaOadJ8xwK
    UPI7gz61E3BfT8+HTYatX4AERyELeC83smrsexTTUsx+SXpuxBJx4XsmXCeGVhS2
    20M4+Xv42QxXvQyXIBNQcDO9R8ycz2Jb3fdwwQIDAQABAoIBAQCIuTqI3qu9l8vF
    Ac7cbiizwm0LhpEDLl3AL8t1D5+5VZ5awuxoVTnzpahughd4K7bu7AYU5jRHRaR5
    kRoaUZmJ1dgro4PU+j5Ir8QIzp23YjqCswQmeXUg50HpSTSwt1T1zoaKvBDa6nuT
    OXPtcd2dxBACU09Ws8hU8eUet2hkDcE/HQS7YLOyztNGrltYjQ8kHR4CBj1JOggq
    d6IybYABDTKqDd9OptiokjWrtYP6VvfWV6Bqgq7gze4KOyakjQBZLtQI+8auTfSX
    gXlwWoZuSO7y/MoopD9IPI+zHgxts/dx+fBxTCjupKBGTemTlnIrc4BMX8ruOHSe
    QByy+C6tAoGBAPewqj0oKjrqh9c9llxzd/6lyiPh1N7cMv44UL+h2u6GtVMwKD8/
    J1AXkmQAmDk5W3+BuWEGyevNkfxGysfG80JI3uuVd+Oi7Iv6mGwzYAzya2weouye
    Ax0fV4fQeT3DydHGsVIoYXx0e4saWcEAbt8fpkKi0coYXjjVduOImRfHAoGBAMgH
    BsMG4cI3vQkb2q6zHH3sVbS9GK4hr1dMev7xX9rfGwqe47eknnMOE1SB5NS2NaaM
    9+iryCZJgxTtZUxWjS9WPSJ9450wHUf5XfiIfgFGR971EE97YZmv8cJzcOfiHm7X
    flGQ7ykEH0hSufRYPMq4BZ0T3SKQyeD72HGv1AM3AoGBAO1YjMktw8nRE3pduce9
    ni6WD61yqdkkiHiy3i3Dm1cWHosoimiQy8sjy1OofjXXkKYOWOVw6+zZgBqOe6IU
    MuZBjduRzuCDLsizyXtlf5Tod6eTc+vpPnKZpfau/n8BLlOmYiSoLUJlHD2fcoJP
    N+73FQqlmwJdd2xeoR5HtuvhAoGAJQgP+2k5wIAbMiWC/dbRDosDbvuXJx27XXke
    SDadnWKymevCkswaPYi8kWee2raFBjmQ5/Vtj5EKgIRWvaREbSAVH16ZFg/DTADh
    odJ7KXc+dQt/oodgEVjedDZ1D6jwI2snyqf/buOBex09qfvv/UPGXkdAKFcP2OQn
    NRztLk8CgYEAh96tybPro/7d55SKMthdNhcmSCgkX2Y4jJ4QWUv5IWEV7fF4TzVP
    Tob9DCImze8i9kJR2Ls+8A7KjFpx3sk++ZW2L04CMS4uvimzLEzltGjnrz60jVCT
    Umj3TruSkAwqAP/mTa/Z03KqiQPBvm787nPdGfFuxftAxDeE7alNZoY=
    -----END RSA PRIVATE KEY-----
  basedomain: apps.cluster-szxjh.szxjh.sandbox1303.opentlc.com # TODO change this to your domain!!!
  baseUrl: https://redhat-developer-hub-user29.apps.cluster-szxjh.szxjh.sandbox1303.opentlc.com/ # TODO change this to your domain!!!
type: Opaque

