# home page url: https://jfokus-app-1.com
# callback url: https://redhat-developer-hub-rh-ee-mvandepe-dev.apps.apps.cluster-vmdtr.vmdtr.sandbox2284.opentlc.com/api/auth/github/handler/frame


kind: Secret
apiVersion: v1
metadata:
  name: rhdh-secrets-github-credentials
  namespace: demo-project #project-namespace
stringData:
  RHDH_GITHUB_ORGANIZATION: "workshop-devhub"
  RHDH_GITHUB_APP_ID: "1131599"
  RHDH_GITHUB_APP_CLIENT_ID: "Iv23liP34q0TMv2MtaHf"
  RHDH_GITHUB_APP_CLIENT_SECRET: "f0354b816c66d142c79f7efc33101c09255a1889"
  RHDH_GITHUB_APP_PRIVATE_KEY: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEA33Ov7+wUr/jeJHXaTwzSMDDIdwthHkckgmozhKgrspbdvEnk
    YWLB4iiMaQdQQ/E0hVZDVkgo+5rlt7Z03adHC4NKgjqOG79d7vurm1e9QA8zVv7I
    rV0mmsiY7vQmYFLjzOaVqFabp+i7YEDsxd9sKeZWd3Jjt292pFxRPlfehc9VlV/J
    0B4HtY9PNROdps+CIIVtkNqUni6YR3xR2x7Rs+gcq70rDwgzSys7/4fDl9ig/91N
    k3+1cLAW4Eqkhg+IevL3bDo/Ug7VxelLMPKFvupgy8FLpHwQFeYydn760tiWceLZ
    7k7AGsKTjrIo359a/n5GIehyBv+IEOXeZ/+6lQIDAQABAoIBAQCh7u7Dimz7kfk6
    pwXMX9g7AD9mtiJtlNUKhfhL3Ku+QsLyXwJY6P7k7MnEm345nqWXM4qdDrJUlE6B
    soJC16UO3Ni0Q8cUqLxkIpKcgxstP1bPZtj7ehQt+82I7fqZt7hKl5hBZHJtXqXb
    /XEZfO6f9sMW0RkeqHJsblKaQYeLo/jIwZY1wYjRyOqVXmt7fc9a7Yh4VswmvANf
    D18vRzZeRvKmYm7BilsqkRwDaFwbxUahCJWUKMijUOic+3aa8FDRE6B/ydt9defb
    z1b5IP3vN6wJVGCyhS26ckzrVuaxduzWiXb+/A6ndb1JOCAaoNQSj2rsgRbaA0CX
    c1HsJjdBAoGBAPkvrMG/HLO1w1fqt/w6OTHZJkz3Tu6R4Y/DOiRLqLxn3msJu7NC
    ncUIsj1B87H8GMwKI4W3aylHoeq2l9+VdRvAL4e4p/98rw93GCRJZQo4QpK88x5D
    ki+FBqmucv+sH2TVzVtQxxlO9wVLR36++XqF9xK9Mf5FCNScveL7oVUNAoGBAOWP
    3rKEdrN2ZzNQTaIVDgvBUw6AFhu3t7x3b8yF+PKAPWQoicSefxT7ojzHR1ZPg6ox
    VZMNwQRyT1yGINamVSxf1wQCYls4GnuEACZfrYbSmBdbyQuyL99WxycU2MC7FYaH
    cuXQFXftB1meMKYJqMiji1faU2f6yT95sp7KfampAoGAE//rkbFREGtqPkgsdCYI
    KSQQmuTOhP9YZz14ESmxZU3A4D5rvjt+hi3ogFomwQZGxzmZGEZcZ3fEWx5EmkFY
    oN2P8wizEyJiuo8IdQEfBu71COn5aVhrBz1aB4xk1nhuHJ28WbPmBvX7hYVBO78A
    LwFJj0t4E7xetRHPe8ROcpECgYBOnO0rfxdTL8n5lZdwWPt9ZQ/3WD+58Dk4jkI3
    7O0qxmW/pe4/6fMlEWMmoyu3z/UL1Gc0u7IMvsSUr84RE9b5Ijz0v4hFKrpO8A5J
    FdzL3dR9s03u9m9UcVgz9vyfS7H8Zuge8RpY/k/VDcolIgut4eu3Ayoq4oQGe7uC
    i19rOQKBgQDWcZBdRxR0KhVkK0ETMsVMBTftrKEUYauMrrctYtAjQXDk18DB+r2t
    5r7mBD8cWNgT7waqIoUOYcO8MygQzUyWDoEoZRFvL8QOmIY4gPPu7Vw0Zxt6XKCt
    xNPxBfvblGqSFhEoUVHHuVXeYRzz3g3F72PRNrKxiunWiG7rRERtLw==
    -----END RSA PRIVATE KEY-----
  basedomain: apps.apps.cluster-vmdtr.vmdtr.sandbox2284.opentlc.com # TODO change this to your domain!!!
  baseUrl: https://redhat-developer-hub-rh-ee-mvandepe-dev.apps.apps.cluster-vmdtr.vmdtr.sandbox2284.opentlc.com/ # TODO change this to your domain!!!
type: Opaque

