apiVersion: rhdh.redhat.com/v1alpha1
kind: Backstage
metadata:
  name: developer-hub
  namespace: demo-project
spec:
  application:
    appConfig: # location where the application configuration file can be added in later training exercises
      mountPath: /opt/app-root/src
    extraFiles:
      mountPath: /opt/app-root/src
    replicas: 1
    route: # enable an external route to access Developer Hub
      enabled: true
  database:
    enableLocalDb: true
  extraEnvs:
    envs:
    # Disabling TLS verification (e.g., when working with self-signed certificates)
    #- name: NODE_TLS_REJECT_UNAUTHORIZED
    #  value: '0'
  deployment:
    patch:
      spec:
        template: # patch in order to cache the installation and speed up the startup of the dynamic plugins
          spec:
            volumes:
              - $patch: replace
                name: dynamic-plugins-root
                persistentVolumeClaim:
                  claimName: dynamic-plugins-root