kind: Secret
apiVersion: v1
metadata:
  name: rhdh-secrets
  namespace: demo-project
stringData:
  BACKEND_SECRET: averysecretpassword
  basedomain: apps.cluster-tkgmm.tkgmm.sandbox2743.opentlc.com # TODO change this to your domain!!!
type: Opaque