kind: Secret
apiVersion: v1
metadata:
  name: rhdh-secrets-github-credentials
  namespace: demo-project
stringData:
  RHDH_GITHUB_ORGANIZATION: "" # TODO complete me
  RHDH_GITHUB_APP_ID: "......" # TODO complete me
  RHDH_GITHUB_APP_CLIENT_ID: "......." # TODO complete me
  RHDH_GITHUB_APP_CLIENT_SECRET: "........" # TODO complete me
  RHDH_GITHUB_APP_PRIVATE_KEY: |  # TODO complete me - entire value of the downloaded .pem file
    -----BEGIN RSA PRIVATE KEY-----
    ...
    ...
    ...
    ...
    ...
    -----END RSA PRIVATE KEY-----
type: Opaque